# Generated by Django 5.1 on 2024-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=250)),
                ('amount_lent', models.IntegerField()),
                ('date_lent', models.DateField()),
                ('interest', models.FloatField()),
            ],
        ),
    ]
