# Generated by Django 5.1 on 2024-08-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
