# Generated by Django 5.1 on 2024-08-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_alter_borrower_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
