# Generated by Django 5.1 on 2024-09-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_borrower_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='total_amount_to_be_paid',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=1000),
            preserve_default=False,
        ),
    ]
