# Generated by Django 5.1 on 2024-09-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_borrower_total_amount_to_be_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='total_amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
