# Generated by Django 5.1 on 2024-09-14 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_alter_borrower_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=250)),
                ('farmer_cost', models.IntegerField()),
                ('labour_expenses', models.IntegerField()),
                ('vehicle_expenses', models.IntegerField()),
                ('other_expenses', models.IntegerField()),
                ('total_profit_or_loss', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
