# Generated by Django 5.1 on 2024-09-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0011_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='patti',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
