# Generated by Django 5.1 on 2024-09-14 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0012_farmer_patti'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=250)),
                ('investment', models.IntegerField()),
                ('pesticides_expenses', models.IntegerField()),
                ('labour_expenses', models.IntegerField()),
                ('other_expenses', models.IntegerField()),
                ('income', models.IntegerField()),
                ('present_profit_or_loss', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
